# Generated by Django 3.2.20 on 2023-08-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='excerpt',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='directions',
        ),
    ]
